# Generated by Django 3.0.6 on 2020-06-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0002_auto_20200602_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('artist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='artist_app.Artist')),
                ('profile', models.BooleanField(verbose_name='Is my profile')),
            ],
            bases=('artist_app.artist',),
        ),
    ]
