# Generated by Django 3.0.6 on 2020-06-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0003_myprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyProfile',
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('artist_app.artist',),
        ),
    ]
