# Generated by Django 3.0.6 on 2020-06-04 16:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0004_auto_20200604_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a description of the artwork', max_length=1000)),
                ('medium_technique', models.CharField(help_text='Enter the medium used in this art-piece', max_length=30, verbose_name='medium/technique')),
                ('date', models.DateField(help_text='When was this artwork made', verbose_name='')),
                ('image', models.ImageField(upload_to='images/', verbose_name='')),
                ('project', models.ForeignKey(help_text='Select a project for this artwork', on_delete=django.db.models.deletion.DO_NOTHING, to='artist_app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ArtWorkInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular artwork across whole archive', primary_key=True, serialize=False)),
                ('bought_by', models.CharField(max_length=200)),
                ('bought_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('n', 'Not for sale'), ('o', 'Being exhibited'), ('a', 'Available'), ('r', 'Reserved'), ('s', 'Sold')], default='n', help_text='ArtWork availability', max_length=1)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist_app.ArtWork')),
            ],
            options={
                'ordering': ['bought_date'],
            },
        ),
        migrations.RemoveField(
            model_name='artpieceinstance',
            name='artpiece',
        ),
        migrations.DeleteModel(
            name='ArtPiece',
        ),
        migrations.DeleteModel(
            name='ArtPieceInstance',
        ),
        migrations.AddField(
            model_name='artist',
            name='artworks',
            field=models.ManyToManyField(blank=True, null=True, to='artist_app.ArtWork'),
        ),
    ]
