# Generated by Django 3.0.6 on 2020-06-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0005_auto_20200604_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='photograph',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='portfolio',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
