# Generated by Django 3.0.6 on 2020-06-04 16:55

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0006_auto_20200604_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkinstance',
            options={'ordering': ['sold_date']},
        ),
        migrations.AlterModelOptions(
            name='myprofile',
            options={'verbose_name_plural': 'My Profile'},
        ),
        migrations.RenameField(
            model_name='artworkinstance',
            old_name='bought_date',
            new_name='sold_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='dates',
        ),
        migrations.AddField(
            model_name='artist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='gallery',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photograph',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='portfolio',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='represented_by',
            field=models.ForeignKey(blank=True, help_text='Select a gallery that represents the artist, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artist_app.Gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='address',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logos/'),
        ),
    ]
