# Generated by Django 3.0.6 on 2020-06-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist_app', '0007_auto_20200604_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of the artwork', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='medium_technique',
            field=models.CharField(blank=True, help_text='Enter the medium used in this art-piece', max_length=30, null=True, verbose_name='medium/technique'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Select a project for this artwork', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='artist_app.Project'),
        ),
        migrations.AlterField(
            model_name='artworkinstance',
            name='bought_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
